### ISSUE TITLE
Add dark theme in app

### ISSUE THREAD

**Issue by gouri-panda** [gouri-panda/Forkify#2]
Right now we have only a light theme. In order to. improve the user experience we should add both a dark theme and a light theme.
* Expected behavior
Users can select both a light theme or dark theme by a toggle switch

**Comment by Michaela115** [comment]
Hi, could I work on this assignment?

**Comment by gouri-panda** [comment]
@Michaela115  I don't understand. Can you translate to English?

**Comment by thinkswell** [comment]
@gouri-panda , Hey, I can do this, can you assign this task to me.
Thank You.

**Comment by gouri-panda** [comment]
@thinkswell please go ahead!

**Comment by thinkswell** [comment]
@gouri-panda  Hey, I have added dark mode and switch button, you can review it :), check PR #8

**Comment by Michaela115** [comment]
Hi, sorry but I dont know make it.
________________________________
Od: Krishna Vishwakarma <notifications@github.com>
Odoslané: nedeľa 4. októbra 2020 23:10
Komu: gouri-panda/Forkify <Forkify@noreply.github.com>
Kópia: Michaela Horváthová <michaela.horvathova@student.tuke.sk>; Mention <mention@noreply.github.com>
Predmet: Re: [gouri-panda/Forkify] Add dark theme in app (#2)


@gouri-panda<https://github.com/gouri-panda> Hey, I have added dark mode and switch button, you can review it :), check PR #8<https://github.com/gouri-panda/Forkify/pull/8>

**Comment by gouri-panda** [comment]
@Michaela115 it's ok.Thank you for interest in the project.
