### ISSUE TITLE
Css breaks in the app

### ISSUE THREAD

**Issue by gouri-panda** [gouri-panda/Forkify#5]
* Steps to reproduce
open the app in the web
see the CSS will break
* Expected behavior 
CSS shouldn't break

**Comment by AhmadShaaban** [comment]
can you assign this to me ?

**Comment by gouri-panda** [comment]
sure @AhmadShaaban please go-ahead. consider yourself assigned.

**Comment by somtookaforr** [comment]
is this still available

**Comment by gouri-panda** [comment]
@Wavist No, it's resolved.
